# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20160917_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.TextField(default=b'Author Authorson'),
        ),
        migrations.AddField(
            model_name='book',
            name='finishedOn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='startedOn',
            field=models.DateField(blank=True, null=True),
        ),
    ]
